using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using bluedragon.multipaltform.sol.control;
using bluedragon.multipaltform.sol.weixin.bll;
using bluedragon.multipaltform.sol.weixin.entity;
using DevExpress.XtraTreeList.Columns;
using DevExpress.XtraTreeList.Nodes;

namespace bluedragon.multipaltform.sol.weixin.ui
{
    public partial class FrmMenuManage2 : BaseForm
    {
        #region Fields
        private WXMenuBll _bll = new WXMenuBll();
        #endregion

        public FrmMenuManage2()
        {
            ApplySkin("McSkin");
            InitializeComponent();
            LoadData();
            repositoryItemComboBox1.Items.AddRange(new string[] { "click", "view", "scancode_waitmsg" });
            // This line of code is generated by Data Source Configuration Wizard
            //gridControl1.DataSource = new System.Collections.Generic.List<bluedragon.multipaltform.sol.weixin.entity.WXMenu>();
        }

        /// <summary>
        /// 获取微信菜单数据（临时Json)
        /// </summary>
        private void LoadData()
        {
            IList<WXMenu> menus = _bll.GetWXMenus().ToList();

            //tlMenu.DataSource = menus;
            AddMenuToTl(null, menus);
        }

        /// <summary>
        /// 加载微信菜单到TreeList中
        /// </summary>
        /// <param name="pNode"></param>
        /// <param name="obj"></param>
        private void AddMenuToTl(TreeListNode pNode, IEnumerable<WXMenu> menus)
        {
            try
            {
                tlMenu.Nodes.Clear();
                TreeListColumn column = tlMenu.Columns.AddField("菜单名称");
                column.Visible = true;
                var rootMenus = from menu in menus
                                where menu.ParentMenuID == 0
                                select menu;
                foreach (var rootMenu in rootMenus)
                {
                    TreeListNode node = tlMenu.AppendNode(rootMenu.MenuID, null);
                    node.Tag = rootMenu;
                    node.SetValue(column, rootMenu.MenuTitle);
                    var childMenus = from menu in menus
                                     where menu.ParentMenuID == rootMenu.MenuID
                                     select menu;
                    foreach (var childMenu in childMenus)
                    {
                        TreeListNode childNode = node.TreeList.AppendNode(childMenu.MenuID, node);
                        childNode.Tag = childMenu;
                        childNode.SetValue(column, childMenu.MenuTitle);
                    }
                    tlMenu_AfterFocusNode(null, null);
                }
                
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void tlMenu_AfterFocusNode(object sender, DevExpress.XtraTreeList.NodeEventArgs e)
        {
            WXMenu menuNode = (WXMenu)tlMenu.FocusedNode.Tag;
            IEnumerable<WXMenu> menus = (from menu in _bll.GetWXMenus()
                                         where menu.MenuID == menuNode.MenuID
                                         select menu).ToList();

            gridControl1.DataSource = menus.Count() == 0
                ? new List<WXMenu>() { new WXMenu() { ParentMenuID = menuNode.ParentMenuID } }
                : menus;
        }

    }
}
